# Generated by Django 4.2.6 on 2023-10-29 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('iidcaja', models.BigAutoField(db_column='iIdCaja', primary_key=True, serialize=False)),
                ('inrocaja', models.IntegerField(db_column='iNroCaja')),
                ('dfechaapertura', models.DateTimeField(db_column='dFechaApertura', default=django.utils.timezone.now)),
                ('dfechacierre', models.DateTimeField(blank=True, db_column='dFechaCierre', null=True)),
                ('fmontoapertura', models.DecimalField(db_column='fMontoApertura', decimal_places=2, max_digits=8)),
                ('fmontocierre', models.DecimalField(db_column='fMontoCierre', decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sobservaciones', models.CharField(db_column='sObservaciones', default='', max_length=2000)),
            ],
            options={
                'db_table': 'cajas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('iidcliente', models.BigAutoField(db_column='iIdCliente', primary_key=True, serialize=False)),
                ('snombrecliente', models.CharField(db_column='sNombreCliente', max_length=191)),
                ('sapellidocliente', models.CharField(db_column='sApellidoCliente', max_length=191)),
                ('idni', models.IntegerField(db_column='iDNI')),
                ('iidestado', models.IntegerField(db_column='iIdEstado')),
                ('semail', models.CharField(db_column='sEmail', max_length=50)),
                ('stelefono', models.CharField(db_column='sTelefono', max_length=15)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comprobantes',
            fields=[
                ('iidcomprobante', models.BigAutoField(db_column='iIdComprobante', primary_key=True, serialize=False)),
                ('snombrecomprobante', models.CharField(db_column='sNombreComprobante', max_length=191)),
                ('sdescripcion', models.CharField(db_column='sDescripcion', max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comprobantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('iidempleado', models.BigAutoField(db_column='iIdEmpleado', primary_key=True, serialize=False)),
                ('snombre', models.CharField(db_column='sNombre', max_length=191)),
                ('sapellido', models.CharField(db_column='sApellido', max_length=191)),
                ('idni', models.IntegerField(db_column='iDNI')),
                ('iidestado', models.IntegerField(db_column='iIdEstado')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('iidmesa', models.BigAutoField(db_column='iIdMesa', primary_key=True, serialize=False)),
                ('inromesa', models.IntegerField(db_column='iNroMesa')),
                ('iidestado', models.IntegerField(db_column='iIdEstado')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mesas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('iidsucursal', models.BigAutoField(db_column='iIdSucursal', primary_key=True, serialize=False)),
                ('snombre', models.CharField(db_column='sNombre', max_length=191)),
                ('iidestado', models.IntegerField(db_column='iIdEstado')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sucursales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('iidtipocomprobante', models.BigAutoField(db_column='iIdTipoComprobante', primary_key=True, serialize=False)),
                ('snombretipocomprobante', models.CharField(db_column='sNombreTipoComprobante', max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_comprobante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('iidtipoempleado', models.BigAutoField(db_column='iIdTipoEmpleado', primary_key=True, serialize=False)),
                ('stipoempleado', models.CharField(db_column='sTipoEmpleado', max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('iidtipomovimiento', models.BigAutoField(db_column='iIdTipoMovimiento', primary_key=True, serialize=False)),
                ('stipomovimiento', models.CharField(db_column='sTipoMovimiento', max_length=191)),
            ],
            options={
                'db_table': 'tipo_movimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoPedidos',
            fields=[
                ('iidtipopedido', models.BigAutoField(db_column='iIdTipoPedido', primary_key=True, serialize=False)),
                ('stipo', models.CharField(db_column='sTipo', max_length=191)),
                ('iidestado', models.IntegerField(db_column='iIdEstado')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_pedidos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoProductos',
            fields=[
                ('iidtipoproducto', models.BigAutoField(db_column='iIdTipoProducto', primary_key=True, serialize=False)),
                ('snombretipoproducto', models.CharField(db_column='sNombreTipoProducto', max_length=191)),
                ('iidestado', models.IntegerField(db_column='iIdEstado')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('iidventa', models.BigAutoField(db_column='iIdVenta', primary_key=True, serialize=False)),
                ('inroventa', models.IntegerField(db_column='iNroVenta')),
                ('dfechaventa', models.DateTimeField(db_column='dFechaVenta')),
                ('fmontoventa', models.DecimalField(db_column='fMontoVenta', decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('iidcaja', models.ForeignKey(db_column='iIdCaja', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.cajas')),
                ('iidempleado', models.ForeignKey(db_column='iIdEmpleado', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.empleados')),
            ],
            options={
                'db_table': 'ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('iidproducto', models.BigAutoField(db_column='iIdProducto', primary_key=True, serialize=False)),
                ('snombreproducto', models.CharField(db_column='sNombreProducto', max_length=191)),
                ('sdescripcion', models.CharField(db_column='sDescripcion', max_length=191)),
                ('istock', models.IntegerField(db_column='iStock')),
                ('dprecio', models.IntegerField(db_column='dPrecio')),
                ('iidestado', models.IntegerField(db_column='iIdEstado')),
                ('surl', models.CharField(db_column='sUrl', max_length=250)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('iidtipoproducto', models.ForeignKey(db_column='iIdTipoProducto', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.tipoproductos')),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('iidpedido', models.BigAutoField(db_column='iIdPedido', primary_key=True, serialize=False)),
                ('inropedido', models.IntegerField(db_column='iNroPedido')),
                ('dfechapedido', models.DateTimeField(db_column='dFechaPedido')),
                ('iidestado', models.IntegerField(db_column='iIdEstado')),
                ('itotal', models.IntegerField(db_column='iTotal')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('iidcliente', models.ForeignKey(db_column='iIdCliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.clientes')),
                ('iidempleado', models.ForeignKey(db_column='iIdEmpleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.empleados')),
                ('iidmesa', models.ForeignKey(db_column='iIdMesa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.mesas')),
                ('iidtipopedido', models.ForeignKey(db_column='iIdTipoPedido', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.tipopedidos')),
            ],
            options={
                'db_table': 'pedidos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='mesas',
            name='iidsucursal',
            field=models.ForeignKey(db_column='iIdSucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.sucursales'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='iidtipoempleado',
            field=models.ForeignKey(db_column='iIdTipoEmpleado', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.tipoempleado'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetallePedidos',
            fields=[
                ('iiddetallepedido', models.BigAutoField(db_column='iIdDetallePedido', primary_key=True, serialize=False)),
                ('icantidad', models.IntegerField(db_column='iCantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iidpedido', models.ForeignKey(db_column='iIdPedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.pedidos')),
                ('iidproducto', models.ForeignKey(db_column='iIdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.productos')),
            ],
            options={
                'db_table': 'detallepedidos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComprobanteVentas',
            fields=[
                ('iidcomprobanteventa', models.BigAutoField(db_column='iIdComprobanteVenta', primary_key=True, serialize=False)),
                ('dfechaemision', models.DateTimeField(db_column='dFechaEmision')),
                ('fimporte', models.DecimalField(db_column='fImporte', decimal_places=2, max_digits=8)),
                ('iidestado', models.IntegerField(db_column='iIdEstado')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('iidcomprobante', models.ForeignKey(db_column='iIdComprobante', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.comprobantes')),
                ('iidventa', models.ForeignKey(db_column='iIdVenta', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.ventas')),
            ],
            options={
                'db_table': 'comprobante_ventas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='comprobantes',
            name='iidtipocomprobante',
            field=models.ForeignKey(db_column='iIdTipoComprobante', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.tipocomprobante'),
        ),
        migrations.AddField(
            model_name='cajas',
            name='iidempleado',
            field=models.ForeignKey(db_column='iIdEmpleado', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.empleados'),
        ),
        migrations.AddField(
            model_name='cajas',
            name='iidsucursal',
            field=models.ForeignKey(db_column='iIdSucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.sucursales'),
        ),
        migrations.AddField(
            model_name='cajas',
            name='iidtipomovimiento',
            field=models.ForeignKey(db_column='iIdTipoMovimiento', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.tipomovimiento'),
        ),
    ]
