# Generated by Django 4.2.6 on 2023-10-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0002_alter_pedidos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comprobantes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comprobanteventas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detallepedidos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mesas',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sucursales',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipocomprobante',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoempleado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipomovimiento',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipopedidos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoproductos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'managed': False},
        ),
    ]
