# Generated by Django 4.2.6 on 2023-10-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0003_alter_cajas_options_alter_clientes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajas',
            options={'managed': True},
        ),
    ]
