# Generated by Django 4.2.6 on 2023-10-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0004_alter_cajas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedidos',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='cajas',
            name='fmontocierre',
            field=models.DecimalField(db_column='fMontoCierre', decimal_places=2, max_digits=8, null=True),
        ),
    ]
