# Generated by Django 4.2.6 on 2023-11-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0005_alter_detallepedidos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('iidtipocliente', models.BigAutoField(db_column='iIdTipoCliente', primary_key=True, serialize=False)),
                ('stipocliente', models.CharField(db_column='sTipoCliente', max_length=191)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='detallepedidos',
            options={'managed': False},
        ),
    ]
