# Generated by Django 4.2.6 on 2023-11-11 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0007_alter_clientes_options_alter_tipocliente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='iidtipocliente',
            field=models.ForeignKey(db_column='iIdTipoCliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CarritoApp.tipocliente'),
        ),
    ]
