# Generated by Django 4.2.6 on 2023-11-11 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarritoApp', '0008_clientes_iidtipocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
